"""add locatio col to teams

Revision ID: 1f2a7656edc1
Revises: bc7098e0be1c
Create Date: 2020-06-17 09:58:14.521908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2a7656edc1'
down_revision = 'bc7098e0be1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'location')
    # ### end Alembic commands ###
