"""Second Migration

Revision ID: 91afa6beedb3
Revises: 004429257745
Create Date: 2020-06-18 14:16:57.826075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91afa6beedb3'
down_revision = '004429257745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixtures')
    # ### end Alembic commands ###
