"""create players table

Revision ID: bc7098e0be1c
Revises: 4306d3074cda
Create Date: 2020-06-17 07:01:39.024158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7098e0be1c'
down_revision = '4306d3074cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('playing_position', sa.String(), nullable=True),
    sa.Column('prof_pic_path', sa.String(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
